app:
    resource: "@AppBundle/Controller/"
    type:     annotation
account_register:
    path:     /register
    defaults: { _controller: AppBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: AppBundle:Account:create }